### PR TITLE
Upgrade to Ember 3 + packages

### PR DESCRIPTION
**Pull request by bl4ckm0r3**
Just upgraded Ember to 3.4.2 (latest) and changed firebase logic to use the most up to date library.
I didn't refactor much to avoid making this a huge change.
There is definitely a refactor to be done but on a future PR.

### CODE REVIEW

**Comment by szimek** [comment]
Thank you so much! I'll check it out later this week and deploy it to staging (http://sharedrop-staging.herokuapp.com/) first to test it a bit.

**Comment by bl4ckm0r3** [comment]
Cool! i have done some local test but i am sure you'll have more chances to test it!
Webtorrent is great!if you want I can help, but I'd like to do a refactor pr first so it would make things easier.

**Comment by szimek** [comment]
Thank you so much for taking time to work on this! I did some refactoring (removed fetching private IPs, added eslint, prettier etc) and also updated Ember to the latest version (3.7.x).

**Comment by bl4ckm0r3** [comment]
thank you for updating your app!! i keep loving it!

**Pull request closed without merging**
